services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3001-3003:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    networks:
      - loadbalancing
    deploy:
      replicas: 3

  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    networks:
      - loadbalancing
      
  nginx:
    image: custom-nginx
    ports:
      - 80:80
    networks:
      - loadbalancing
    depends_on:
      - app

volumes:
  todo-mysql-data:
  
networks:
  loadbalancing:
